# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/platform/build-configuration

# Enforce Node.js version
[build]
  # Use a simpler build command that just builds the frontend
  command = "cd quickbite-app && npm install && npm run build"
  node_version = "20.11.1"
  publish = "quickbite-app/dist"

# Environment variables
[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-audit --prefer-offline"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Ensure optional dependencies are installed
  NPM_CONFIG_OPTIONAL = "true"
