# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/platform/build-configuration

# Enforce Node.js version
[build]
  # Use npm install instead of npm ci to handle package-lock.json mismatches
  command = "npm install && node cloudflare-build.js"
  node_version = "18.18.0"
  publish = "dist"

# Environment variables
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--no-audit --prefer-offline"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Ensure optional dependencies are installed
  NPM_CONFIG_OPTIONAL = "true"
