name: Deploy Backend to Railway

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/gh-deploy@v3
        with:
          token: ${{ secrets.RAILWAY_API_TOKEN }}
          projectId: 7dc615b0-b318-406f-8bfe-641f530b3170
          servicePath: quickbite-backend
